### ISSUE TITLE
Casting to string only

### ISSUE THREAD

**Issue by booni3** [calebporzio/sushi#19]
I love this package btw!

One thing I noted so far was the fact all data is cast as a string, even if it is set and/or defined as an integer. i.e.

```php
protected $rows = [
    ['name' => 'Amazon', 'tenant_aware' => true, 'allow_jobs' => 100, 'every_seconds' => 60],
    ['name' => 'Ebay', 'tenant_aware' => true, 'allow_jobs' => 100, 'every_seconds' => 60]
];

protected $casts = [
    'allow_jobs' => 'integer',
    'every_seconds' => 'integer',
];
```

Its not a big issue at this stage, but thought I would mention it.

**Comment by LukeTowers** [comment]
I was initially thinking of having a separate method or some sort of mapping to make the migration smarter, but using the $casts array is actually a brilliant way of handling that.

**Comment by calebporzio** [comment]
Yeah, I actually ran across this myself and just did a quick `$casts` like you did here. Maybe this is something that belongs in the README?

**Comment by booni3** [comment]
@calebporzio are you saying that casts does work? In my case I am setting a bool or integer on the rows array, but even with casts in place everything is outputting as a string.

**Comment by calebporzio** [comment]
Sushi should now more intelligently set column types in the database if it encounters and integer or float, etc...

Try this in 2.0. Re-open if still an issue.

**Comment by James-ONeill** [comment]
I've just come up against this issue in 2.0.

For the model below, the `price` field always gets converted to a string in the model. Setting the schema seems to work on the database side, as if I set it to `float` then the price strings include a trailing `.0`. Nothing seems to work to convert the price to an integer including setting `$casts` or `getPriceAttribute`.

```php
class Product extends Model
{
    use Sushi;

    protected $rows = [
        ['name' => 'A', 'price' => 5500],
        ['name' => 'B', 'price' => 11000],
        ['name' => 'C', 'price' => 22000],
    ];

    protected $schema = [
        'price' => 'integer',
    ];
}
```
