### ISSUE TITLE
Missing sushi config file

### ISSUE THREAD

**Issue by innoflash** [calebporzio/sushi#22]
https://github.com/calebporzio/sushi/blob/70ad2b2e1dc4a808ef1667405e09b0c1671efd22/src/Sushi.php#L20

Forgive me if i am too blind or ignorant on how Sushi works but i cant find the ```sushi.php``` config file or you are just adding it somewhere in your project as a service

**Comment by nathanheffley** [comment]
Did you run `php artisan vendor:publish`? That is the command usually responsible for publishing config files.

**Comment by beblife** [comment]
The package does not come with a default config file to publish right now.
But looking at the code you highlighted, you can create your own `config/sushi.php` in your Laravel  app and assign the config values there if you like.

**Comment by innoflash** [comment]
Yeah, it makes sense because i see a default value of ```sushi``` set on that highlighted line
