### ISSUE TITLE
`is_numeric` is too generic to determine column types

### ISSUE THREAD

**Issue by skollro** [calebporzio/sushi#30]
Really great package!

One thing I noticed: The `is_numeric` function I think is not the best solution to determine the column type, since it casts e.g. a string value like `01` automatically to `1` which might cause trouble. I would suggest to use something like `is_int($value)` here.

An even better solution could be to let the developer specify an array of column types that are used for the schema.

https://github.com/calebporzio/sushi/blob/70ad2b2e1dc4a808ef1667405e09b0c1671efd22/src/Sushi.php#L78

**Comment by calebporzio** [comment]
Should be fixed in 2.0
