### ISSUE TITLE
load $rows data from external json file

### ISSUE THREAD

**Issue by muhsenmaqsudi** [calebporzio/sushi#42]
I'm trying to load the protected $rows property from a json file but it doesn't work as i expected,
when i try to fetch the Model It works fine when using tinker, but in code & controller it give a **server is currently unable to handle this request.**

```php
class City extends EloquentModel
{
    use \Sushi\Sushi;

    protected $rows;

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $path = app_path('Shared/Data/cities.json');
        $cities = json_decode(file_get_contents($path), true);
        $this->rows = $cities;
    }
}
```

**Comment by faustbrian** [comment]
You should be using https://github.com/calebporzio/sushi#using--getrows for your use-case instead of this workaround to fill the rows property.

**Comment by muhsenmaqsudi** [comment]
> You should be using https://github.com/calebporzio/sushi#using--getrows for your use-case instead of this workaround to fill the rows property.

tnx it's working now using the getRows method
