### ISSUE TITLE
PHP Error:  Call to a member function query() on null

### ISSUE THREAD

**Issue by internethelden** [calebporzio/sushi#43]
Hello there,

I tried to use your package, but unfortunately I am getting this error:

> PHP Error:  Call to a member function query() on null in /Users/foobar/Dev/Laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1051

This is my model:

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Sushi\Sushi;

class Category extends Model
{
    use Sushi;

    protected $client;

    protected $rows = [
        [
            'abbr' => 'NY',
            'name' => 'New York',
        ],
        [
            'abbr' => 'CA',
            'name' => 'California',
        ],
    ];

}
```

The lines in Model.php are:

```
    /**
     * Get a new query builder instance for the connection.
     *
     * @return \Illuminate\Database\Query\Builder
     */
    protected function newBaseQueryBuilder()
    {
        return $this->getConnection()->query();
    }
```

specifically it's `return $this->getConnection()->query();`. But why is it even being called?

**Comment by internethelden** [comment]
Solved it: There was something wrong with my cache.

**Comment by JunaidQadirB** [comment]
@internethelden did you clear the cache? I'm getting the same error.
