### ISSUE TITLE
Cannot access array at index 0 in multidimensional arrays

### ISSUE THREAD

**Issue by bzrncev** [calebporzio/sushi#44]
For the following rows in State model:

```php
protected $rows = [
    ['NY', 'New York'],
    ['CA', 'California'],
];
```
if we try `dd(\App\State::first()[1]);`  - "New York" is returned, but for `dd(\App\State::first()[0]); ` null is returned.

**Comment by LukeTowers** [comment]
@bzrncev why are you trying to access the data in that way? Why not define your data in multidimensional arrays to be able to access via properties?

**Comment by calebporzio** [comment]
I don't think this is a Sushi related issue. Eloquent doesn't work that way.
