### ISSUE TITLE
Eager loading doesn't work with non-integer IDs

### ISSUE THREAD

**Issue by owenandrews** [calebporzio/sushi#45]
Trying to eager load using `User::with('type')->first()` when using strings as IDs returns `null`.

Works as expected when used via dynamic properties: `User::first()->type`.

Sushi Model:
```
protected $casts = ['id' => 'string'];

protected $rows = [
    ['id' => 'student', 'name' => 'Student', 'amount' => 2000],
    ['id' => 'adult', 'name' => 'Adult', 'amount' => 4500],
    ['id' => 'family', 'name' => 'Family', 'amount' => 5500],
];
```

User Model:
```
public function type()
{
    return $this->belongsTo('App\MembershipType');
}
```

Works as expected when using integer IDs.

**Comment by ryangjchandler** [comment]
Have you tried to set the `$keyType` property on your user model to to `string` And `$incrementing` to `false`?

**Comment by mokhosh** [comment]
The problem seems to be deeper that that https://github.com/calebporzio/sushi/issues/61

**Comment by Naoray** [comment]
> Have you tried to set the `$keyType` property on your user model to to `string` And `$incrementing` to `false`?

This solved it for me. Thanks @ryangjchandler! :bow:

**Comment by markwalet** [comment]
@owenandrews Can you verify the given solution works for you? It worked for me and @Naoray. So we can close this issue

**Comment by mokhosh** [comment]
Yes, tested everything and it all works. We can close this.

**Comment by owenandrews** [comment]
Yep that solved it, apologies for not closing this issue sooner. Thanks everyone!
