### ISSUE TITLE
Artisan command to refresh tables

### ISSUE THREAD

**Issue by jtgrimes** [calebporzio/sushi#48]
I was thinking it would be handy to have an artisan command to refresh all tables (and/or a named table) that could be included in a deploy script. While the data in a Sushi model shouldn't change often, in my use case I find myself adding new rows as I roll out new features and want a way to be sure that everything is refreshed on deploy.

I'm not sure when I'll have time to put a PR together, so I thought I'd throw the issue out there and let anyone else take a crack at it.

**Comment by ryangjchandler** [comment]
> I was thinking it would be handy to have an artisan command to refresh all tables (and/or a named table) that could be included in a deploy script. While the data in a Sushi model shouldn't change often, in my use case I find myself adding new rows as I roll out new features and want a way to be sure that everything is refreshed on deploy.
> 
> I'm not sure when I'll have time to put a PR together, so I thought I'd throw the issue out there and let anyone else take a crack at it.

If the file has been modified, then Sushi will detect that and compare it against the time stamp on the SQLite file. It will then invalidate the cache and refresh it.

**Comment by calebporzio** [comment]
What @ryangjchandler said.

However, if you DO run into something, I'd be open to a PR for that command.

Thanks!

**Comment by jtgrimes** [comment]
Looks like my problem was caused by changing some constant values

```
    protected $rows = [
        ['target' => Import::TARGET_STANDARD, 'object' => Translation::OBJECT_USER,],
        ['target' => Import::TARGET_ADMIN, object' => Translation::OBJECT_OFFICER,],
...
```
I changed the value of OBJECT_OFFICER and the cache didn't refresh because I hadn't actually changed the model file. Not sure if that's gonna be a common enough case to make a command for, but it might be something to point people at if they're troubleshooting a cache issue.
