### ISSUE TITLE
No such table: XXX (SQL: select * from "XXX")

### ISSUE THREAD

**Issue by ConsoleTVs** [calebporzio/sushi#49]
```
Illuminate/Database/QueryException with message 'SQLSTATE[HY000]: General error: 1 no such table: tests (SQL: select * from "tests")'
```

```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Test extends Model
{
    use \Sushi\Sushi;

    protected $rows = [
        ['id' => 1, 'name' => 'Erik']
    ];
}

```

```php
>>> App\Models\Test::all();
```

**Comment by ConsoleTVs** [comment]
**Solution:** Enable SQLite from php.ini

**Comment by shiroamada** [comment]
Hi, I also having the same issue. My phpinfo() show that sqlite already installed.
or anything I missed? how to enable?
macos  10.15.3
using brew install php74

![image](https://user-images.githubusercontent.com/2062946/76397534-30ac0900-63b6-11ea-815a-8a9d73a9b023.png)

**Comment by ConsoleTVs** [comment]
Is your sqlite installed? I think its php-sqlite

**Comment by shiroamada** [comment]
Yes, my sqlite is working fine. in my .env file I set as
```
DB_CONNECTION=sqlite
DB_DATABASE=/Users/shiro/Sites/sushi/database/database.sqlite
```
It is working fine, i can run migration without any issue.

![image](https://user-images.githubusercontent.com/2062946/76415223-cb671080-63d3-11ea-8d1f-a7b0c808a2f2.png)

**Comment by ConsoleTVs** [comment]
Make sure you have it also on the server php. Php normally have a php-cli and php. php-cli is used for migrations, etc. while php is used in the server. You have to enable it in both.

**Comment by morpheus7CS** [comment]
Hey @shiroamada,

Sushi will use the in-memory SQLite database, not the local database located in /Users/shiro/Sites/sushi/database/database.sqlite.

Kind regards,
g

**Comment by shiroamada** [comment]
OK, I found out the solution after read the source code.
I have to go to

This is from source code I get the clue
`$cacheDirectory` = realpath(config('sushi.cache-path', storage_path('framework/cache')));

I manual delete this file, 
`/Users/shiro/Sites/sushi/storage/framework/cache/sushi-app-monkey.sqlite`
and request again, then I have the correct error, if not it database is always empty that's the reason why can't select * from xxx table.

Thanks guys!
