### ISSUE TITLE
ErrorException Array to string conversion

### ISSUE THREAD

**Issue by josiahke** [calebporzio/sushi#54]
\vendor\calebporzio\sushi\src\Sushi.php:130 -   static::insert($rows);

my API call response looks like this, after setting json_decode(object, true)

array:14 [▼
  0 => array:19 [▶]
  1 => array:19 [▶]
  2 => array:19 [▶]
  3 => array:19 [▶]
  4 => array:19 [▶]
  5 => array:19 [▶]
  6 => array:19 [▶]
  7 => array:19 [▶]
  8 => array:19 [▶]
  9 => array:19 [▶]
  10 => array:19 [▶]
  11 => array:19 [▶]
  12 => array:19 [▶]
  13 => array:19 [▶]
]

for some reasons I get an error - ErrorException Array to string conversion

**Comment by calebporzio** [comment]
Do any of those `array:19` arrays contain sub-arrays? Eloquent will throw that error when trying to insert a row that has an array as a value.

You likely need to do more json_encodeing or extracting out that data.

Closing for now.
