### ISSUE TITLE
Getting a QueryException

### ISSUE THREAD

**Issue by K2ouMais** [calebporzio/sushi#57]
Hello everybody,

I have a fresh Laravel installation and I wanted to try Sushi for the first time.

I installed it like it is written here in the Readme file.

When trying to see the result of the collection I get a QueryException error:
![QueryExceptionError](https://user-images.githubusercontent.com/52510455/76847633-a5fa5c80-6842-11ea-93bf-2adf8de4b5d9.png)

This is my Model:
![Model](https://user-images.githubusercontent.com/52510455/76847658-b4487880-6842-11ea-9a4b-e4d8deb27203.png)

This is my Route:
![Route](https://user-images.githubusercontent.com/52510455/76847668-b8749600-6842-11ea-9098-510cdd0e39f7.png)

I am doing something wrong? My Model has about 300 entries, but even if I got it to just 4-5, It still doesnt work.

Need your help, please.

Thank you in advance

**Comment by faustbrian** [comment]
`could not find driver` usually means that you don't have the sqlite extension for PHP installed.

**Comment by K2ouMais** [comment]
It was exactly the problem. It never came into my mind, to look at the PHP Extensions.

It seems my list is just to long for Sushi. Now I am getting "General error: 1 too many SQL variables".

The array is almost 2000 rows long and SQLite seems to have a limitation to only 999.

I guess I have to go back into MySQL again. It was worth a try.

Thank you for your help.
