### ISSUE TITLE
String id column?

### ISSUE THREAD

**Issue by mokhosh** [calebporzio/sushi#61]
When I set custom string ids for my columns, the id of all items are 0 for some reason:

```php
use Sushi;
    protected $rows = [
    [
        'id' => 'ltr',
        'title' => 'Left to Right',
    ],
    [
        'id' => 'rtl',
        'title' => 'Right to Left',
    ],
];
```

**Comment by litvinjuan** [comment]
I don't know if this will help, buy maybe you should also set the following attributes on your Eloquent Models for non-integer ids:

```php
public $incrementing = false;
protected $keyType = 'string';
```

**Comment by mokhosh** [comment]
@litvinjuan I've used integer id's to get it going, but I'll try this next time I ran into a similar problem. Thank you so much.

**Comment by markwalet** [comment]
I think this solves the problem. May I suggest we close this issue?

**Comment by markwalet** [comment]
@mokhosh Can we close this as a duplicate of #45 ?

**Comment by mokhosh** [comment]
Don't know about duplicate, but tested everything and it all works. We can close this.
