### ISSUE TITLE
Whats the license?

### ISSUE THREAD

**Issue by kaidesu** [calebporzio/sushi#73]
Hello!

Curious what the license is for this package? Would like to credit the package in our CMS for its use :+1: I know this was sponsorware at one point but has been released as open source since then, according to the readme.

Thanks for all you do!

**Comment by LukeTowers** [comment]
Good point, we are planning on integrating something similar into @octobercms shortly too, so if a license could get added to the repo that would be great @calebporzio.

**Comment by morpheus7CS** [comment]
Hey @kaidesu and @LukeTowers,

the `composer.json` file specifies the license as MIT. I've added a PR, so that the `LICENSE.md` file is also included in the repository, to avoid future misunderstandings.

Kind regards,
g

**Comment by LukeTowers** [comment]
Thanks @morpheus7CS, I hadn't gotten around to digging that deep into it yet :)

**Comment by calebporzio** [comment]
Thanks!
